name: create_tag CI

on:
  workflow_dispatch:
    inputs:
      release_tag_version:
        description: 'Enter Tag Version'
        required: true
        type: string
  
jobs:
  create_tag:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install package Manager
      run: yarn install
    - name: Print Tag version
      run: |
        echo "Tag Version: $TAG"
      env: 
        TAG: ${{ inputs.release_tag_version}}
    - name: Setup Github Config
      run: | 
        git config user.name "Github Actions Bot KLTR"
        git config user.email "<>"
    - name: Create tag
      run: |
        git tag ${{ inputs.release_tag_version }}
        git push origin ${{ inputs.release_tag_version }}
