name: create_tag CI

on:
  workflow_dispatch:
    inputs:
      release_tag_version:
        description: 'Enter Tag Version'
        required: true
        type: string
  
jobs:
  create_tag:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install package Manager
      run: yarn install
